name: Tests for PR

on:
  pull_request:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy pylint pytest pydantic requests requests-mock httpx pytest-httpx pytest-asyncio pytest-cov

      - name: Run mypy to generate cache
        run: mypy py3xui || true

      - name: Install missing stub packages
        run: mypy --install-types --non-interactive

      - name: Run mypy
        run: mypy py3xui

      - name: Run pylint
        run: pylint py3xui

      - name: Run pytest with coverage
        run: pytest --cov=py3xui --cov-branch --cov-report xml